## NumPy
- short for Numerical Python, is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently
- Performance:
  - Operations on NumPy arrays are more efficient than operations on standard Python lists, especially for large datasets. 
  - This efficiency comes from the fact that NumPy is implemented in C, and its arrays use contiguous memory blocks.
  - FAST
  - Convenient (alots of functionalities)
  - less Memory
  
- Broadcasting: NumPy allows operations on arrays of different shapes, making it very flexible and powerful.

- Integration: It can be easily integrated with other libraries, such as SciPy, Pandas, and Matplotlib, to enhance its functionality

In [2]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [29]:
#flaot array

arr = np.array([[1,2,3],[4,5,6],[3,2,1]], dtype = np.float64)  #float64 (8 bytes per element).
arr

#complex datatype

arr = np.array([[1,2,3],[4,5,6],[3,2,1]], dtype = complex)  #float64 (8 bytes per element).
arr
print("the shape of arr is",arr.shape)

the shape of arr is (3, 3)


### why we use numpy array instead of python list
- because numpy array take less size\


In [10]:
import time 
import sys

#python list
pylist = range(1000)
print("space occupy by python list is",sys.getsizeof(0)*len(pylist))

#let check how many space take by array
np_array = np.arange(1000)
print("space occupy by numpy array is",np_array.size*np_array.itemsize)

space occupy by python list is 28000
space occupy by numpy array is 4000


## 2-dimensional (2D) array
- A 2-dimensional (2D) array, also known as a matrix, is a collection of elements arranged in rows and columns, forming a grid-like structure. In Python's NumPy library, a 2D array is essentially an array of arrays where each sub-array represents a row in the matrix.


### Characteristics of a 2D Array
- Rows and Columns: 
  - It consists of multiple rows and columns. The number of rows and columns can vary, but each row must have the same number of columns for it to be considered a proper 2D array.
  - Shape: The shape of a 2D array is described by a tuple (n, m), where n is the number of rows and m is the number of column

In [21]:
#2d array

arr1_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

a = arr1_2d
b = arr2_2d


#operations
#shape

print("the shape of the matix is ",a.shape)

#Element-wise Addition
a = arr1_2d + 10


#Matrix Multiplication (dot product)
dotpro = np.dot()


the shape of the matix is  (3, 3)


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## Multidimentional Array
- Multidimensional arrays are a core feature of NumPy and are commonly used in scientific computing, data analysis, and machine learning. NumPy provides a powerful set of tools for creating, manipulating, and performing operations on multidimensional arrays.
- Multidimensional arrays are an extension of 2-D matrices and use additional subscripts for indexing. A 3-D array, for example, uses three subscripts. The first two are just like a matrix, but the third dimension represents pages or sheets of elements.



In [7]:
import numpy as np
arr_3d = np.array([[[1,2,3],[4,2,5],[1,3,2]],[[1,3,1],[3,1,4],[5,2,4]]])
arr_3d.shape


#randomly
arr_3d_random = np.random.rand(3,4,5)
arr_3d_random

(2, 3, 3)

# Matrix Multiplication 

## Element-wise Multiplication:
- Multiplies each corresponding element of two arrays.
- Uses the * operator.
- Arrays must have the same shape.

## Dot Product (Matrix Multiplication):
- computes the matrix product of two arrays.
- Uses the np.dot() function or the @ operator.
- Follows matrix multiplication rules where the number of columns in the first matrix must equal the number of rows in the second matrix.

In [24]:
#Element-wise Multiplication:

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,1,3],[4,2,6],[7,1,3]])
print("element wise multiplication is \n",a*b)

element wise multiplication is 
 [[ 4  2  9]
 [16 10 36]
 [49  8 27]]


In [30]:
# Dot Product (Matrix Multiplication):

a = np.array([[1,2,3],[4,5,6]])             # no of columns of first matrix == no of rows of second matrix 
b = np.array([[4,1,3],[4,2,6],[7,1,3]])
dot_pro = np.dot(a,b)
print(f"the dot product of matrix a and b is \n {dot_pro}")


the dot product of matrix a and b is 
 [[33  8 24]
 [78 20 60]]


## vectorize vs non vectorize 


In [28]:
import numpy as np
import time 

x = np.random.rand(10000000)
w = np.random.rand(10000000)
t = time.time()
z = np.dot(w,x)
b = 0

duration = time.time() - t
print(f"{duration* 1000} ms")

#non vectorize 

t1 = time.time()
for i in range(len(x)):
    z = 0
    z += w[i] * x[i]
z += b

duration1 = time.time() - t1
print(f"time taken through non _vectorize version{duration* 1000} ms")
#time taken through non _vectorize version 1.1449713706970215


10.000467300415039 ms
time taken through non _vectorize version10.000467300415039 ms


In [39]:
#zero array
x =  np.zeros((3,2),dtype = np.int64)
x

#one's array
x1 = np.ones((3,3) , dtype = np.int64)
x1


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [41]:
x2 = np.arange(10)
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np.char module in NumPy 
-  The np.char module in NumPy provides a collection of vectorized string operations, allowing you to perform string   operations on entire arrays of strings efficiently. These functions are particularly useful for handling and manipulating large arrays of strings without needing explicit loops. Here are some of the key functions provided by np.char:

In [58]:
#1 np.char.add():
F_name = np.array(["baber","shayan"])
L_name = np.array(["Raheem","Raheem"])
print("concatination of two string arrays :",np.char.add(F_name,L_name))  #concatination of two string arrays : ['baberRaheem' 'shayanRaheem']

#2 np.char.center():
print(np.char.center("hello",20,fillchar = "-"))   #-------hello--------

#3 np.char.multiply():
print(np.char.multiply(F_name,2))                 #['baberbaber' 'shayanshayan']

#4 np.char.capitalize():
print(np.char.capitalize("baber"))                #Baber

#5 np.char.title():
print(np.char.title("This is numpy tutorial"))   #This Is Numpy Tutorial

#6 np.char.lower():
print(np.char.lower("BABER RAHEEM"))             #baber raheem

#7 np.char.upper(): 
print(np.char.upper("baber raheem"))             #BABER RAHEEM

#8 np.char.split():
arr = np.array(["hello world","welcome","congratulation"])
print(np.char.split(arr)) #[list(['hello', 'world']) list(['welcome']) list(['congratulation'])]

#9 np.char.replace()
print(np.char.replace(np.array(["hello world! how are you doing today"]),"o", "0"))

concatination of two string arrays : ['baberRaheem' 'shayanRaheem']
-------hello--------
['baberbaber' 'shayanshayan']
Baber
This Is Numpy Tutorial
baber raheem
BABER RAHEEM
[list(['hello', 'world']) list(['welcome']) list(['congratulation'])]
['hell0 w0rld! h0w are y0u d0ing t0day']
