## Array Multiplication & Reshaping

In [5]:
import numpy as np
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#1D to 2D array
x_mod = x.reshape(3,3)
x_mod 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
x_mod.shape

#to flate the array again
#The flatten() method returns a copy of the array collapsed into one dimension.
print(x_mod.flatten())


[0 1 2 3 4 5 6 7 8]


In [2]:
import numpy as np
# ravel():
# The ravel() function returns a contiguous flattened array. Unlike flatten(), ravel() returns a view whenever possible.
x_1 = np.arange(9).reshape(3,3)

print(x_1)

result = x_1.ravel()
print(result)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [20]:
#Transpose of an array or matrix
matrix = np.array([[1,2,3],[4,6,1]])
print(matrix)

print("traspose of matrix")
print(matrix.T)

[[1 2 3]
 [4 6 1]]
traspose of matrix
[[1 4]
 [2 6]
 [3 1]]


In [24]:
#The resize() function changes the shape and size of the array in-place.
#note it modifiy the orignal array

matrix = np.array([[1,2,3],[4,6,1]])
matrix.resize((3,2))
print("after resize",matrix)

after resize [[1 2]
 [3 4]
 [6 1]]


## Numpy Arithmatic Operations

In [25]:
#addition

x = np.arange(9).reshape(3,3)
y = np.arange(9).reshape(3,3)

addition = np.add(x,y)
print(addition)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [27]:
#Subtraction:
sub = np.subtract(x,y)
print(sub)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
#multiplication
mul = np.multiply(x,y)
print(mul)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [30]:
#divide
div = np.divide(x,y)
print(div)

[[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


C:\Users\Babar Raheem\AppData\Local\Temp\ipykernel_11056\2307280885.py:2: RuntimeWarning: invalid value encountered in divide
  div = np.divide(x,y)


In [31]:
#Summation:
result = np.sum(x)
print(result)

36


## joining arrays in numpy
--note : In numpy, axis=0 refers to rows, and axis=1 refers to columns.

In [24]:
# arr1 = np.random.randint(2,3)
arr1 = np.random.randint(0, 10, size=(2, 3))
print("first array ", arr1)

print("\n")

arr2 = np.random.randint(0,10,(2,3))
print("second array",arr2)

print("\n")

print("concatenate array at axis =1")
con_arr = np.concatenate((arr1,arr2), axis = 1)   #column wise 
print(con_arr)
print("the size of the concatenate array () is" , con_arr.shape)


print("concatenate array at axis =0")
con_arr = np.concatenate((arr1,arr2), axis = 0)   #row wise 
print(con_arr)
print("the size of the concatenate array  is" , con_arr.shape)


first array  [[3 8 7]
 [7 8 5]]


second array [[4 9 8]
 [0 5 0]]


concatenate array at axis =1
[[3 8 7 4 9 8]
 [7 8 5 0 5 0]]
the size of the concatenate array () is (2, 6)
concatenate array at axis =0
[[3 8 7]
 [7 8 5]
 [4 9 8]
 [0 5 0]]
the size of the concatenate array  is (4, 3)


# Reshaping and Resizing an array

## Reshape: 
- Changes the shape of an array without altering its data and keeps the total number of elements the same. It does not modify the original array.
- reshaped_arr = arr.reshape((new_shape))

In [ ]:
#Reshaping..

import numpy as np

# Original array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to 3x2
reshaped_arr = arr.reshape((3, 2))
print("Reshaped array:\n", reshaped_arr)


## Resizing 
- Resize: Changes the shape and potentially the size of an array, modifying the original array. It fills new elements with zeros if the size increases and truncates elements if the size decreases.

In [35]:
arr1 = np.random.randint(0, 10, (2,3))
print(arr1) 

#resizing 
print("\n")
print("after resizing the array")
update_arr1 = np.resize(arr1,(3,3))
print(update_arr1)

[[0 6 1]
 [0 7 2]]


after resizing the array
[[0 6 1]
 [0 7 2]
 [0 6 1]]


# sqrt() and standard deviation

In [43]:
arr1 = np.array([[1,2,3],[4,5,3]])
arr1
sqr_arr = np.sqrt(arr1)
print(sqr_arr)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 1.73205081]]


In [45]:
#standard deviation 
print("standard deviation")
standard_dev = np.std(arr1)
print(standard_dev)

standard deviation
1.2909944487358056


In [46]:
#calculating standard deviation manually
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Step 1: Compute the mean
mean = np.mean(arr)
print("Mean:", mean)

# Step 2: Compute squared differences
squared_diffs = (arr - mean) ** 2
print("Squared Differences:", squared_diffs)

# Step 3: Compute the mean of squared differences (variance)
variance = np.mean(squared_diffs)
print("Variance:", variance)

# Step 4: Take the square root of the variance (standard deviation)
std_dev = np.sqrt(variance)
print("Standard Deviation:", std_dev)


Mean: 3.0
Squared Differences: [4. 1. 0. 1. 4.]
Variance: 2.0
Standard Deviation: 1.4142135623730951


# log


In [48]:
arr = np.array([1, 2, 3, 4, 5])
print(np.log10(arr))

#we can find log2
print(np.log2(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


In [3]:
import numpy as np
arr = np.random.rand(10,10)
print(arr)
arr.shape

[[0.91630307 0.51024134 0.59217186 0.85181405 0.23019516 0.03836796
  0.85304011 0.94675704 0.09667946 0.81823535]
 [0.1752362  0.99163931 0.06141615 0.12236425 0.35944816 0.98342579
  0.64850474 0.62703238 0.65764814 0.80990709]
 [0.83103909 0.86974102 0.61680358 0.51712243 0.75466705 0.38416414
  0.65269962 0.38681707 0.55303423 0.98964664]
 [0.61422952 0.9960456  0.85338023 0.55910883 0.25488323 0.85851757
  0.55893684 0.50802521 0.63726521 0.82039102]
 [0.34242066 0.96173045 0.73388399 0.74561779 0.67519368 0.51464128
  0.00290946 0.20280641 0.29985225 0.89462912]
 [0.63782565 0.51006815 0.36785811 0.06481669 0.57144309 0.40545482
  0.62699549 0.30123189 0.85830476 0.68371165]
 [0.58396226 0.69130919 0.72828128 0.50827528 0.99526631 0.57699176
  0.91207627 0.1829032  0.65689589 0.22827515]
 [0.27354263 0.99152201 0.07512248 0.95488863 0.72108698 0.01502607
  0.71894572 0.38901717 0.43825405 0.3634158 ]
 [0.92410265 0.66862533 0.64341636 0.56000184 0.29701716 0.60735619
  0.91648161

(10, 10)